### ISSUE TITLE
JWT for `yii\filters\auth\AuthMethod`

### ISSUE THREAD

**Issue by frontbear** [yiisoft/auth-jwt#1]
- About JWT(JSON Web Tokens [RFC 7519]):
[https://jwt.io](https://jwt.io/)

- Yii2 RESTful Web Services Authentication:
[https://www.yiiframework.com/doc/guide/2.0/en/rest-authentication](https://www.yiiframework.com/doc/guide/2.0/en/rest-authentication)

**Comment by samdark** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement JWT authentication](https://trello.com/c/OuBWeanx/100-implement-jwt-authentication)
