### ISSUE TITLE
Which jwt library?

### ISSUE THREAD

**Issue by demonking** [yiisoft/auth-jwt#2]
@rustamwin suggests [lcobucci/jwt](https://github.com/lcobucci/jwt) in this issue from yiisoft/yii-web

https://github.com/yiisoft/yii-web/issues/114#issuecomment-552824205

The Problem is, we will need version v4.x (php 7.3) but this version is not stable and we don't know, how long it will takes.

**Comment by samdark** [comment]
How about https://github.com/yiisoft/yii2-authclient/issues/217?

**Comment by demonking** [comment]
So you mean using [web-token/jwt-framework] ?

i'm not against it, i wanted only to mentioned it :)

[web-token/jwt-framework] : https://github.com/web-token/jwt-framework

**Comment by samdark** [comment]
Yes. I mean it.

**Comment by samdark** [comment]
#1
