### ISSUE TITLE
JWT encrypted with RS256 instead of HS256

### ISSUE THREAD

**Issue by eluhr** [yiisoft/auth-jwt#35]
### What steps will reproduce the problem?

I am using an RS256 algorithm instead of the (default) HS256 algorithm. RS256 uses a  public/private key pair instead of a secret. The [TokenManager](https://github.com/yiisoft/auth-jwt/blob/cc62114b5868ae2357e68732b9c00521cd442ad1/src/TokenManager.php) only implements the possibility to define a secret but not a public or private file path or encryption key.

`config/web/auth.php`
```php
<?php

declare(strict_types=1);

/** 
 * @var array $params
 */

use Jose\Component\Signature\Algorithm\RS256;
use Yiisoft\Auth\Jwt\TokenManagerInterface;
use Yiisoft\Auth\Jwt\TokenManager;
use Yiisoft\Auth\AuthenticationMethodInterface;
use Yiisoft\Auth\Jwt\JwtMethod;

return [
    TokenManagerInterface::class => [
        '__class' => TokenManager::class,
        '__construct()' => [
             // `secret` not needed for this algorithm, but must be defined for the token manager constructor
            'secret' => $params['yiisoft/auth-jwt']['secret'],
            'algorithms' => [new RS256()]
           // where do i define the public/private key file path or the encryption key?
        ]
    ],
    AuthenticationMethodInterface::class => JwtMethod::class
];

```

### What is the expected result?

A possibility to define a public and private key file path for the token manager and the secret not to be a default

### What do you get instead?

No possibility to use a JWT with RS256 algorithm

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev-master#cc62114
| PHP version      |  7.4.12
| Operating system | Docker yiisoftware/yii-php:7.4-apache

**Comment by samdark** [comment]
@rustamwin refactored code. Now it should be alright. Please provide feedback when tested. Thanks.
