### ISSUE TITLE
Update `web-token/*` library

### ISSUE THREAD

**Issue by random-rage** [yiisoft/auth-jwt#71]
### What steps will reproduce the problem?
`composer update`

### What is the expected result?
Outdated packages are not installed.

### What do you get instead?
composer: Package `web-token/* is abandoned`, you should avoid using it. Use `web-token/jwt-library` instead.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0.1
| PHP version      | 8.3
| Operating system |macOS

**Comment by trexanhvn** [comment]
Does anyone check this?

**Comment by samdark** [comment]
No. Did you?

**Comment by trexanhvn** [comment]
@samdark I checked, and it is still a warning when running Composer. I do not know how to update for new version.
